name: Build & Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore /p:DevPluginDir="${{ runner.temp }}\devPlugins"

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
